version: '3'
services:
  blocktrain-runner:
    image: ${IMAGE}/blocktrain-runner:${TAG}
    platform: linux/amd64
    environment:
      DEBUG: ${DEBUG}
      PORT: ${PORT}
      ADDRESS: ${ADDRESS}
    build:
      target: base
    ports:
      - "${PORT:-3000}:${PORT:-3000}"